import { NextRequest, NextResponse } from "next/server";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db";
import { ApiError, getClientIp, requireRole, withErrorHandling } from "@/lib/http";
import { driverCreateSchema } from "@/lib/validation";
import { driverToDto } from "@/lib/serialize";
import { hashPassword } from "@/lib/auth";
import { tempPassword } from "@/lib/tokens";
import { driverWelcomeEmail } from "@/lib/mailer";
import { queueMail } from "@/lib/mail-queue";
import { getBaseUrl } from "@/lib/base-url";
import { audit } from "@/lib/audit";

const ACTIVE_ROUTE_STATUSES = ["ASSIGNED", "IN_PROGRESS"];

/** GET /api/drivers — list all drivers with their active route counts (ADMIN). */
export const GET = withErrorHandling(async () => {
  await requireRole("ADMIN");

  const drivers = await prisma.user.findMany({
    where: { role: "DRIVER", deletedAt: null },
    orderBy: { name: "asc" },
    include: {
      _count: {
        select: {
          assignedRoutes: {
            where: { status: { in: ACTIVE_ROUTE_STATUSES }, deletedAt: null },
          },
        },
      },
    },
  });

  return NextResponse.json({
    items: drivers.map((d) => driverToDto(d, d._count.assignedRoutes)),
  });
});

/** POST /api/drivers — create a driver account (ADMIN). */
export const POST = withErrorHandling(async (req: NextRequest) => {
  const admin = await requireRole("ADMIN");
  const body = driverCreateSchema.parse(await req.json());

  const existing = await prisma.user.findFirst({
    where: { email: body.email, deletedAt: null },
    select: { id: true },
  });
  if (existing) {
    throw new ApiError(409, "A user with this email already exists", "EMAIL_TAKEN");
  }

  const autoGenerated = !body.password;
  const plainPassword = body.password ?? tempPassword();
  const passwordHash = await hashPassword(plainPassword);

  let driver;
  try {
    driver = await prisma.user.create({
      data: {
        name: body.name,
        email: body.email,
        phone: body.phone ?? null,
        passwordHash,
        role: "DRIVER",
        status: "ACTIVE",
        mustChangePassword: true,
      },
    });
  } catch (err) {
    // The email column is unique across all rows (including soft-deleted ones).
    if (err instanceof Prisma.PrismaClientKnownRequestError && err.code === "P2002") {
      throw new ApiError(409, "A user with this email already exists", "EMAIL_TAKEN");
    }
    throw err;
  }

  const baseUrl = await getBaseUrl();
  queueMail(
    driverWelcomeEmail({
      to: driver.email,
      name: driver.name,
      email: driver.email,
      tempPassword: plainPassword,
      loginUrl: `${baseUrl}/login`,
    }),
  );

  await audit({
    userId: admin.id,
    action: "driver.create",
    entity: "User",
    entityId: driver.id,
    detail: { name: driver.name, email: driver.email },
    ip: getClientIp(req),
  });

  return NextResponse.json(
    {
      driver: driverToDto(driver, 0),
      tempPassword: autoGenerated ? plainPassword : undefined,
    },
    { status: 201 },
  );
});
